config/routes.rb
UrlShortener::Application.routes.draw do

  get '/:id(/:desc)' => 'shorts#show', :as => 'short'
  get '/' => 'shorts#new', :as => 'new_short'
  post '/' => 'shorts#create', :as => 'shorts'

  

end

app/models/short.rb
class Short < ActiveRecord::Base
   
   attr_accessible :long, :desc
   attr_accessor :desc

  validates :long,
		:presence => true,
		:format => {
		:with => %r{^http://},
		:message => "Only HTTP links allowed!"
		}

  def to_param
    
    if self.desc.nil?
      s36_id
       else

      "#{s36_id}/#{self.desc.parameterize}"
    end

  end

  def s36_id
  
    self.id.to_i.to_s(36)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/shorts_controller.rb
class ShortsController < ApplicationController

	def new
		@short = Short.new

		respond_to do |format|
		format.html 
		end

	end

  def create
    @short = Short.new(params[:short])

    respond_to do |format|
    if @short.save
    format.html { render action: "show" } 
    else
    format.html { render action: "new" }
    end
    end

  end

  def show
    @short = Short.find(params[:id].to_i(36))

    respond_to do |format|
    format.html { redirect_to @short.long }
    end
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shorts_helper.rb
module ShortsHelper
end

app/views/home/index.html.erb
<h1>Shorten your URL<h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<div id="header">

<h1>URLShortener</h1>

</div>
  <title>URLShortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>


<div id="footer">
© 2016 URLShortener.Created By Rajender ,  <a href="https://github.com/nunerajender">Github</a> and
<a href="https://twitter.com/rajender_nune">Twitter</a>
</div

</body>
</html>
<style type="text/css">
body {
    background-color:lightgrey;
}
#header {
    background-color:green;
    color:#f68720;
    text-align:center;
    padding:5px;
}

#footer {
    background-color:green;
    color:white;
    clear:both;
    text-align:center;
   padding:5px;	 
</style>


</body>
</html>

app/views/shorts/_form.html.erb
<%= form_for(@short) do |f| %>
  <% if @short.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@short.errors.count, "error") %> prohibited this short from being saved:</h2>

      <ul>
      <% @short.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Enter Long URL" %><br />
    <%= f.text_field :long %>
  </div>
<br/>
  <div class="field">
    <%= f.label "Description (It will come End of the short url)" %><br />
    <%= f.text_field :desc %>
  </div>
<br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shorts/edit.html.erb
<h1>Editing short</h1>

<%= render 'form' %>

<%= link_to 'Show', @short %> |
<%= link_to 'Back', shorts_path %>

app/views/shorts/index.html.erb
<h1>Listing shorts</h1>

<table>
  <tr>
    <th>Long</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shorts.each do |short| %>
  <tr>
    <td><%= short.long %></td>
    <td><%= link_to 'Show', short %></td>
    <td><%= link_to 'Edit', edit_short_path(short) %></td>
    <td><%= link_to 'Destroy', short, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Short', new_short_path %>

app/views/shorts/new.html.erb
<h1>Create a new short URL</h1>

<%= render 'form' %>

app/views/shorts/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Your URL was shortened</h3>

<p>The new short URL is <%= link_to short_url(@short), short_url(@short) %>.</p>

<p>The URL leads to <%= link_to @short.long, @short.long %>.</p>

<p><%= link_to 'Shorten another URL', new_short_path %></p>